create table HOST(
    HNUM INT NOT NULL AUTO_INCREMENT,
    NAME NVARCHAR(40) NOT NULL UNIQUE,
    DOMAIN NVARCHAR(50) NOT NULL,
    IP NVARCHAR(40) NOT NULL UNIQUE,
    DATE DATETIME,
    PRIMARY KEY(HNUM)
) ENGINE= MYISAM CHARSET=utf8;
